services:
  zelemetry:
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - zelemetry-network
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - .:/app
      - zelemetry_data:/app/build
    env_file:
      - .env

networks:
  zelemetry-network:
    driver: bridge

volumes:
  zelemetry_data:
